---
title: ""
---

## Procedure {#sec-tutorial}

This procedure shows you how to use webCAT using either your own item bank, **or** one of the two item banks that are offered as examples. These include:

1.  a 36 maximum-performance item bank named TCAT, for an Dutch-English Vocabulary test with dichotomous items calibrated using a 2-parameter logistic model

2.  a 19 typical-performance item bank of the PROMIS Pediatric Psychological Stress Experiences (PPSE) questionnaire (self-report; 8-17yrs old; see [Bevans et al., 2018](https://doi.org/10.1093/jpepsy/jsy010)), with 19 polytomous items, calibrated using a graded response model.

::: callout-note
## Note

Throughout this tutorial, a callout banner like this one will be used to guide you through the steps of using one of the **TCAT** or the **PPSE** item banks.
:::

To continue the tutorial using your own item bank, provide an item bank name of your choice (without spaces) and enter the access token you generated.

```{=html}
<div style="
  background-color: rgba(24, 188, 156, 0.1);  /* #18bc9c with 20% opacity */
  border: 1px solid #18bc9c;
  padding: 10px;
">
  <div class="d-flex gap-3 mt-1">
    <fieldset class="flex-fill"> 
    <!-- CAT Name -->
    <div class="form-floating">
    <input type="text" class="form-control" id="catName" placeholder="Test Name">
    <label for="catName">Test Name<sup>*</sup></label>
  </div>
    </fieldset>
    <fieldset class="flex-fill">
    <!-- Personal Key -->
    <div class="form-floating mt-1">
      <input type="password" class="form-control" id="key" placeholder="Token" autocomplete="off">
      <label for="key">Access Token<sup>*</sup></label>
    </div>
    </fieldset>
  </div>
  <p style="margin: 0.85em 0; font-size: 0.75em;"><sup>*</sup> Required field.</p>
</div>  
```
::: callout-note
For the TCAT: Enter `TCAT` as the test name and `Tok1234` as the access token.

For the PPSE: Enter `PPSE` as the test name and `Tok1234` as the access token.
:::

## Step 0: Complete the item bank information file

{{< include step0.qmd >}}

## Step 1: Upload the item bank information file {#sec-step1}

{{< include step1.qmd >}}

## Step 2: Configuration of the test

{{< include step2.qmd >}}

## Step 3: Qualtrics set up

{{< include step3.qmd >}}
