---
#title: "Step 0: Create Itembank Blueprint"
---

This step is required only if you would like to construct your own item bank file. If you would like to use one of the examples, please skip this step and go to Step 1.

It is essential that the file has the correct structure^1^ if you want to use your own item bank. In this step, you can download a blueprint that you can edit and fill in with all the necessary information.

::: {.callout-tip collapse="true"}
## ^1^Details on the item bank structure

The item bank information file must be a Comma-Separated Values (.csv) file, with specific column names and a specific structure. The number of rows should correspond to the number of available items.

-   The first column, labelled `ItemLabel`, must contain the item labels.

-   The second column, labelled `Item`, must contain the item stems.

-   The next columns must contain the response options, labeled `Choice1`, `Choice2`, and so on, up to the number of available choices.\
    **Note:** In this version, all items must have the same number of response options.

-   The next column, labelled `Scores`, must contain the item scores. A possible format for a dichotomous item with 4 response options could be `0100` indicating that the second response option is scored as 1 (e.g., correct answer). For polytomous items the scores should range from `0` up to the total number of categories minus 1, e.g., `0123` for 4 response options.

-   The next columns contain the items' discrimination (slope) parameters.\
    For $l$ dimensions, $l$ columns are required, labelled `a1`, `a2`, etc. For a unidimensional structure, there is only one parameter, and therefore one column labelled `a1.`

-   The next column, labelled `d`, contains the items' difficulty (location or intercept) parameters.
:::

```{=html}
<!-- MAIN HTML PAGE -->
<div style="
  background-color: rgba(24, 188, 156, 0.1);  /* #18bc9c with 20% opacity */
  border: 1px solid #18bc9c;
  padding: 20px;
">
<div class="d-flex gap-3 mt-1">
  <!-- 1st row -->
  <fieldset class="flex-fill">
  <div class="form-floating flex-grow-1">
    <input type="number" class="form-control" id="J" placeholder=" " min="1" value="5">
    <label for="J">Enter the total number of items</label>
  </div>
  </fieldset>
  <fieldset class="flex-fill">
  <div>
    <label for="itemType" class="form-label">Select the item type</label>
    <select class="form-select" id="itemType">
      <option>Dichotomous Items</option>
      <option>Polytomous Items</option>
    </select>
  </div>
  </fieldset>
</div>

<div class="d-flex gap-3 mt-1">
  <!-- 2nd row -->
  <fieldset class="flex-fill">
    <div class="form-floating flex-grow-1 mt-2">
    <input type="number" class="form-control" id="responseOptions" placeholder=" " min="2" value="4">
    <label for="responseOptions">Enter the number of response options</label>
  </div>
  </fieldset>
  <fieldset class="flex-fill">
  <div class="form-floating flex-grow-1 mt-2">
     <input type="number" class="form-control" id="factors" placeholder=" " min="1" value="1">
    <label for="F">Enter the number of dimensions/latent traits</label>
  </div>
  </fieldset>
</div>

  <button class="btn btn-outline-success mt-3" onclick="sendData()">Get Itembank Blueprint</button>
</div>
```
```{=html}
<script>
async function sendData() {
    // create the payload
    const payload = {
      J: document.getElementById("J").value,
      itemType: document.getElementById("itemType").value, //"Dichotomous Items" or "Polytomous Items"
      factors: document.getElementById("factors").value,
      responseOptions: document.getElementById("responseOptions").value
    };

    console.log("Sending JSON:", payload);
    
  try {
    // 1. Send to API and wait for response
    const res = await fetch("https://qualcat.duckdns.org/api/v0/itembank-blueprint", {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(payload)
    });

    // API returns CSV -> get blob
    const blob = await res.blob();
    console.log("Response:", res);
    
    // Create download link
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "itembank_blueprint.csv";
    document.body.appendChild(a);
    a.click();
    a.remove();
    window.URL.revokeObjectURL(url);

  } catch (error) {
    console.error("Error:", error);
    alert("Could not download file.");
  }
}
</script>
```
